apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels: 
    description: "nginx pod"
    app: nginx
    version: "1.0"
    environment: "development"
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80